#+ summary: Find all nanopublications for a given triple pattern, in undefined order
#+ method: GET
#+ pagination: 1000

prefix np: <http://www.nanopub.org/nschema#>

select distinct ?np where {
  graph ?h {
    ?np a np:Nanopublication .
    { ?np np:hasAssertion ?g } union
    { ?np np:hasProvenance ?g } union
    { ?np np:hasPublicationInfo ?g }
  }
  graph ?g {
    ?__subj_iri ?__pred_iri ?__obj_iri .
    ?__subj_iri ?__pred_iri ?__objliteral .
  }
}
