#+ summary: Find all nanopublications signed with the given public key, in undefined order
#+ method: GET
#+ pagination: 1000
#+ endpoint_in_url: False

prefix np: <http://www.nanopub.org/nschema#>
prefix npa: <http://purl.org/nanopub/admin/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?np where {
  graph npa:graph {
    ?np npa:hasHeadGraph ?h .
    ?np npa:creationDay ?__day_iri .
    ?np npa:creationMonth ?__month_iri .
    ?np npa:creationYear ?__year_iri .
    ?np npa:hasValidSignatureForPublicKey ?_pubkey_xsd_string .
  }
}
