#+ summary: Get publication info graph by nanopub identifier
#+ method: GET
#+ endpoint_in_url: False

prefix np: <http://www.nanopub.org/nschema#>
prefix npa: <http://purl.org/nanopub/admin/>

construct {
  ?s ?p ?o
} where {
  graph npa:graph {
    ?_np_iri npa:hasHeadGraph ?h .
  }
  graph ?h {
    ?_np_iri np:hasPublicationInfo ?i .
  }
  graph ?i {?s ?p ?o}
}
