#+ summary: Get all nanopublication that the given index directly contains as elements
#+ method: GET

prefix np: <http://www.nanopub.org/nschema#>
prefix npx: <http://purl.org/nanopub/x/>
prefix npa: <http://purl.org/nanopub/admin/>

select ?elementnp {
  graph npa:graph {
    ?_indexnp_iri npa:hasHeadGraph ?h .
  }
  graph ?h {
    ?_indexnp_iri np:hasAssertion ?index_a .
    ?_indexnp_iri np:hasPublicationInfo ?index_i .
  }
  graph ?index_a {
    optional { ?_indexnp_iri npx:includesElement ?elementnp . }
  }
  graph ?index_i {
    ?_indexnp_iri a npx:NanopubIndex .
  }
}
