#+ summary: Get deep forward links for the given nanopublication
#+ method: GET
#+ pagination: 1000
#+ endpoint_in_url: False

prefix np: <http://www.nanopub.org/nschema#>
prefix npa: <http://purl.org/nanopub/admin/>
prefix dct: <http://purl.org/dc/terms/>

select ?linked_np where {
  graph npa:graph {
    ?linked_np npa:hasHeadGraph ?h .
  }
  graph npa:networkGraph {
    ?_np_iri (!npa:null)+ ?linked_np .
  }
}
