#+ summary: Get the number of nanopublications
#+ method: GET

prefix npa: <http://purl.org/nanopub/admin/>

select (count(?np) as ?count) where {
  graph npa:graph {
    ?np npa:hasHeadGraph ?h .
  }
}
