#+ summary: Get the number of nanopublications, possibly restricted by year, month, or day
#+ method: GET
#+ endpoint_in_url: False

prefix npa: <http://purl.org/nanopub/admin/>

select (count(?np) as ?count) where {
  graph npa:graph {
    ?np npa:hasHeadGraph ?h .
    ?np npa:creationDay ?__day_iri .
    ?np npa:creationMonth ?__month_iri .
    ?np npa:creationYear ?__year_iri .
  }
}
