#+ summary: Get deep back-links for the given nanopublication
#+ method: GET
#+ pagination: 1000
#+ endpoint_in_url: False

prefix npa: <http://purl.org/nanopub/admin/>

select ?linking_np where {
  graph npa:networkGraph {
    ?linking_np (!npa:null)+ ?_np_iri .
  }
}
