#+ method: GET
#+ pagination: 1000
#+ endpoint_in_url: False

prefix np: <http://www.nanopub.org/nschema#>
prefix npx: <http://purl.org/nanopub/x/>
prefix npa: <http://purl.org/nanopub/admin/>
prefix dce: <http://purl.org/dc/elements/1.1/>
prefix dct: <http://purl.org/dc/terms/>
prefix pav: <http://purl.org/pav/>
prefix prov: <http://www.w3.org/ns/prov#>

select ?np ?title ?date where {
  graph npa:graph {
    ?np npa:hasHeadGraph ?h .
    optional { ?np dct:created ?date . }
  }
  graph ?h {
    ?np np:hasPublicationInfo ?i .
  }
  graph ?i {
    ?np a npx:NanopubIndex .
    filter not exists { ?np a npx:IncompleteIndex . }
    optional { ?np dce:title ?title . }
  }
}
order by desc(?date)
