#+ summary: Get publication info graph by nanopub identifier
#+ method: GET

prefix np: <http://www.nanopub.org/nschema#>

construct {
  ?s ?p ?o
} where {
  graph ?h {
    ?_np_iri a np:Nanopublication ;
      np:hasPublicationInfo ?i .
  }
  graph ?i {?s ?p ?o}
}
