#+ summary: Testing with nanopub SPARQL endpoint at Manchester University
#+ endpoint: http://openphacts.cs.man.ac.uk:8890/sparql
#+ method: GET
#+ pagination: 50

select distinct ?Concept where {[] a ?Concept} LIMIT 20
