#+ summary: Testing...
#+ method: GET
#+ pagination: 50

PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX dc: <http://purl.org/dc/terms/>

select ?np ?time where {
  ?np a np:Nanopublication ;
    dc:created ?time .
} LIMIT 10
