#+ summary: Testing with nanopub SPARQL endpoint at Manchester University
#+ endpoint: http://openphacts.cs.man.ac.uk:8890/sparql
#+ method: GET
#+ pagination: 50

PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX dc: <http://purl.org/dc/terms/>

select ?np ?time where {
  ?np a np:Nanopublication ;
    dc:created ?time .
} LIMIT 10
